#!/bin/sh -ex

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
bash miniconda.sh -b -p $HOME/miniconda
source "$HOME/miniconda/etc/profile.d/conda.sh"
hash -r
conda config --set always_yes yes --set changeps1 no
conda update -q conda
# Useful for debugging any issues with conda:
conda info -a

# Replace dep1 dep2 ... with your dependencies
conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION
conda activate testenv
python setup.py install