#!/bin/sh -ex

pylint --version

# Return something other than 0 only if the output of pylint signals 1 (fatal) or 2 (error)
# See https://stackoverflow.com/a/49904607
set -o errexit
set -o nounset
(
    pylint src/tarski || rc=$?;
    exit $(( $rc & 35 )) # fatal=1 | error=2 | usage error=32
)