#!/usr/bin/env bash

set -e
set -x

# python -m coverage combine
# python -m coverage xml
# python -m coverage report -m
bash <(curl -s https://codecov.io/bash) -Z -X gcov -X coveragepy -X search -X xcode -X gcovout -X fix -f coverage.xml